### ISSUE TITLE
Fork / Decision / Join, cannot join on forks correctly

### ISSUE THREAD

**Issue by ndidi-did** [Netflix/conductor#881] opened 2018-11-28 19:16 UTC
We are working on a POC that tests some of the fork/join/decision capabilities of conductor, but I'm running into an issue where the final join before the acknowledgeMailings task can't see any other tasks after the 2 fork branches (email1 and letter1), as shown below:

<img width="353" alt="wf_fork_join" src="https://user-images.githubusercontent.com/45435192/49175956-fc1e5600-f306-11e8-8bf0-d2cae8b24581.png">

[JSON for the above here](https://api.jsonbin.io/b/5bfee81b90a73066ac16f906)

I tried adding test (t1) as a simple http task and then joining on ["test", "lt1"] but it doesn't seem to work, additionally, test (t1) does not even run after the decision.

This flow is working correctly, but it only is joining on ["et1", "lt1"] but I essentially need 

`("et1" OR "et2") AND ("lt1" OR "lt2")`

<img width="385" alt="wf_join" src="https://user-images.githubusercontent.com/45435192/49175568-1b68b380-f306-11e8-8e2b-9e04bb48c94d.png">

[JSON for the above here](https://api.jsonbin.io/b/5bfee903df915b65399970ea)

I'm sure there must be something that I am missing. any help would be greatly appreciated.

Thanks.

**Comment by kishorebanala** [comment] 2019-01-15 00:38
@ndidi-did Thanks for reporting this issue. Somehow, decision task within fork isn't working as expected. The Join task is scheduled along with Fork task, and Join should know tasks it is waiting for, making it static. And hence, all the first tasks within decision works fine, but others wouldn't.

A workaround is to put decision tasks in a sub workflow, and let Join wait on this sub-workflow.

**Comment by jkaipa** [comment] 2019-02-12 21:27
Any update on this issue?

**Comment by jkaipa** [comment] 2019-05-02 20:42
The issue is with this line 
https://github.com/Netflix/conductor/blob/78fae0ed9ddea22891f9eebb96a2ec0b2783dca0/core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java#L324

Need a fix here

`if (SystemTaskType.is(task.getTaskType()) && SystemTaskType.DECISION.name().equals(task.getTaskType())) {
            if (task.getInputData().get("hasChildren") != null) {
                return Collections.emptyList();
            }
        }
`

**Comment by demichej** [comment] 2019-09-04 18:08
We're hitting this as well. @kishorebanala I see your suggestion that you put your decision tasks in a subworkflow. Unfortunately, that just wouldnt be very maintainable for our use case.

Do you know if someone is actively working on a fix for this? Or when there's an ETA for it?

(On a side note, do y'all use Intellij for development? I haven't been able to get my local conductor debugging in Intellij yet)

**Comment by kishorebanala** [comment] 2019-09-12 00:51
@demichej We're swamped at the moment and planning to get to this in early Q4. If you have bandwidth, we'd happy to work with you on this fix.

**Comment by kishorebanala** [comment] 2019-09-12 00:56
@demichej I've setup a IntelliJ Run configuration on Gradle with `Gradle project: conductor:server` and `Tasks: server` to run Conductor server in debug mode locally. It should be applicable to Eclipse as well.

**Comment by demichej** [comment] 2019-10-17 14:40
@kishorebanala sorry, never even replied. Thank you, this worked.

**Comment by apanicker-nflx** [comment] 2019-12-24 00:08
Fixed as part of #1449

**Closed by apanicker-nflx** 2019-12-24 00:08 UTC
Labels: bug, help wanted
