### ISSUE TITLE
Retries and sub-workflows behaviour

### ISSUE THREAD

**Issue by vtzi** [Netflix/conductor#1856] opened 2020-09-06 15:56 UTC
The current workflow retry behaviour (i.e. `POST /workflow/{workflowId}/retry`) doesn't play nice with sub-workflows. 

If we have two workflow definitions (T`x` denotes a simple task):
SF: T1 -> T2 -> T3
PF: T4 -> SUB_WORFLOW(SF) -> T5

Failure in T3 will put SF in failed state and will propagate the error to parent workflow (PF) which will also be put in failed state. 

The current retry behaviour is:
* If PF is retried a new instance of SF is created and the execution starts form T1. This is not desirable since T1/T2/etc may require a lot of resources (not only machine but human in the loop as well), may have side effects, etc. 
* If SF is retried and completes successfully it ends in TERMINATED state since `Parent workflow has been terminated with status FAILED`

Ideally we would like to retry and resume worfklows execution from the point of failure: I see two ways to achieve this:

* Don't propagate the sub workflow error to parent. Instead put the sub-workflow in failed state, leave the SUB_WORKFLOW task in parent in IN_PROGRESS state. In this case the sub-workflow can be retried and resumed from the point of failure and everything will continue working as expected.
* Keep the error propagation to parent but upon parent's retry recurse to sub-workflow and retry/resume these accordingly. This looks more complex and error prone from implementation pov.  

What do you think should be the retry behaviour in presence of sub workflows? Are you open for PRs/changes implementing one of the two options above (or any other way to resume from the point of failure without doing double work)?

BR
  Vlad

**Comment by kishorebanala** [comment] 2020-09-10 00:09
Hey @vtzi , any chance the subworkflow (SF) doesn't have a failure workflow defined in it's definition?

It might be caused by this [line](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1669), which verifies few things on parent workflow, but I believe `StringUtils.isBlank(parentDef.getFailureWorkflow())` shouldn't be there.

> What do you think should be the retry behaviour in presence of sub workflows?

Retrying a subworkflow should put both Subworkflow and Parent workflow in RUNNING state, essentially resuming from where it last stopped. Verifying the above changing and fixing it should make this possible.

> Are you open for PRs/changes

Absolutely. Please send us a PR if you were able to reproduce and fix this.

**Comment by vtzi** [comment] 2020-09-10 07:42
> any chance the subworkflow (SF) doesn't have a failure workflow defined in it's definition?
It doesn't.

> > What do you think should be the retry behaviour in presence of sub workflows?
> 
> Retrying a subworkflow should put both Subworkflow and Parent workflow in RUNNING state, essentially resuming from where it last stopped. Verifying the above changing and fixing it should make this possible.

^^^ This covers the case when you retry the sub-workflow. What about retrying the parent workflow? Currently this creates a new instance of the sub-workflow which is semantically correct (SUB_WORKFLOW task is being retried) but not desirable.

**Comment by kishorebanala** [comment] 2020-09-14 23:23
> What about retrying the parent workflow? Currently this creates a new instance of the sub-workflow which is semantically correct (SUB_WORKFLOW task is being retried) but not desirable.

Correct. Given that Conductor workflow executions are not immutable (yet), retrying a subworkflow (and thus Subworkflow) task would erase the record of Subworkflow, thereby making it hard to trace what happened in failed subworkflow task case.

But, Please feel free to put forward a design proposal for your changes to retrying from parent workflow, and we shall take it from there.

**Comment by vtzi** [comment] 2020-09-19 21:45
I think SUB_WORKFLOW should have an option whether to propagate the failure to the parent. Currently it is propagated and this makes resuming from the failure point in subworkflows when retrying the parent difficult to implement. 

If we have such option these are the possible use cases:
1. The option is `True` (default) - everything behaves as is - no breaking changes are introduced. 
2. The option is `False` - the error is not propagated, the parent workflow stays in `RUNNING` state, the `SUB_WORKFLOW` task in parent stays in `IN_PROGRESS` state. Upon retrying of the failed subworkflow everything continues as expected.

Both options are valid and common in real world. 
1. Sometimes you want to get notified immediately about problems and take actions (e.g. cancelled flight - book another one). That's the error propagation.
2. In other cases it's ok to wait for the problem to be resolved especially if it's out of your control (e.g. post office strike and no mail is getting delivered - you have to wait until the issue is resolved. You may not even know that post office workers were on strike for a week but at the end you'll get your mail/parcels).

BR
  Vlad

PS: For background - we have chain of subworkflows and some of these involve human interactions (i.e. expensive). There are subworfklows like:
`T1  -> TH2 -> T3` where `TH2` is a human-in-the-loop (i.e. implemented by `WAIT` task and communication to external systems) and if there is a failure in `T3` (like network outage), upon retry we definitely don't want to execute `TH2` again but resume from `T3`.

**Comment by kishorebanala** [comment] 2020-09-22 23:28
I like sticking to the defaults and having an option to retry the parent. But, keeping the parent `IN_PROGRESS ` while the sub workflow has failed doesn't makes sense to me. What happens if the subworkflow is never retried? or retried after parent subworkflowTask is timed out.

Instead, how about having an option to `restart` vs `retry` the parent workflow? 
I.e 
-> when the sub workflow fails, we'll keep the existing behavior of terminating the subWorkflow task.
-> when the parent workflow is retried, the subworkflow task will now have an option to `retry` vs `restart` the subworkflow; `retry` being retrying the sub workflow from where it left off with same subworkflowId, and `restart` being the existing behavior of starting the subworkflow from the beginning with a new subworkflowId (default will remain `restart`).
-> when the sub workflow is retried, the parent workflow is put to RUNNING state, and the subWorkflow task to IN_PROGRESS state.

**Comment by vtzi** [comment] 2020-09-23 08:29
This sounds perfect and more consistent then my proposal. Thank you for looking into it. 
What are the next steps?

**Comment by kishorebanala** [comment] 2020-09-28 21:46
@vtzi This is in `enhancement` backlog now. Please feel free to send us a PR if you have bandwidth. Thanks for opening up this discussion.

Here are some additional things to consider when working on this feature:
- Make sure to enforce this new `retry` flag only when subworkflow task is retried. i.e if the subworkflow tasks is being newly executed, even if the configuration has `retry` flag, it should still start a workflow.
- Restart at the moment re-uses the existing workflowId, while the current sub workflow task when re-executed will `recreate` a new sub workflow. Consider this distinction when naming params.
- Please make sure to add enough integration tests in `test-harness` module, given the criticality of this feature.

**Comment by BhavanaJoshi21** [comment] 2021-03-23 03:38
Hello
Can someone provide task and workflow definitions for creating a subworkflow inside a parent workflow. 
Thanks

**Comment by apanicker-nflx** [comment] 2021-03-25 00:07
@BhavanaJoshi21 Please refer the [kitchensink workflow example](https://netflix.github.io/conductor/labs/kitchensink/#definition) in the documentation for an example of a subworkflow task within a parent. Also, the [subworkflow task](https://netflix.github.io/conductor/configuration/systask/#sub-workflow) documentation provides details about a subworkflow task using a workflow definition.

**Comment by apanicker-nflx** [comment] 2021-03-25 00:08
This issue will be fixed as part #2025 . Closing

**Closed by apanicker-nflx** 2021-03-25 00:08 UTC
Labels: enhancement, help wanted
