### ISSUE TITLE
fix npe

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2061] opened 2021-01-22 13:27 UTC
We encountered NPE in the production environment and repaired it. Please evaluate whether it is necessary to deal with it.
The PR [#2060](https://github.com/Netflix/conductor/pull/2060)

**Comment by apanicker-nflx** [comment] 2021-02-02 00:11
Hi @andyyumiao , testing out the codepaths for the subworkflow execution, I was unable to reproduce a case where the subworkflow task would be null. While the PR itself is safe to merge because defensive programming inherently is helpful, I would like to better understand the scenario when you encountered this and fix at the root cause as well. 

Please attach the workflow defs, execution etc that can be used to reproduce this case. Will keep the PR open for now and try and bundle together the fixes.

**Comment by kishorebanala** [comment] 2021-03-29 23:50
Marking this as closed; Please feel free to reopen if this is still relevant.

**Closed by kishorebanala** 2021-03-29 23:50 UTC
