### ISSUE TITLE
What is the notation to refer previous task output without knowing the task name

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#986] opened 2019-02-11 15:44 UTC
Hi,

I have a decision task having 3 branches and If I want to use the outcome of decision as a next task input,
How can I refer the previous task output(i.e decision case output) in next task.

Could you please help on this.

**Comment by gsambasiva** [comment] 2019-02-11 17:19
Example JSON is,

{
  "name": "decide_task",
  "taskReferenceName": "decide1",
  "inputParameters": {
    "case_value_param": "${workflow.input.movieType}"
  },
  "type": "DECISION",
  "caseValueParam": "case_value_param",
  "decisionCases": {
    "Show": [
      {
        "name": "setup_episodes",
        "taskReferenceName": "se1",
        "inputParameters": {
          "movieId": "${workflow.input.movieId}"
        },
        "type": "SIMPLE"
      }
    ],
    "Movie": [
      {
        "name": "setup_movie",
        "taskReferenceName": "sm",
        "inputParameters": {
          "movieId": "${workflow.input.movieId}"
        },
        "type": "SIMPLE"
      }
    ]
  },
  {  
    "name":"get_movie_episodes",
    "taskReferenceName":"outcome",
    "inputParameters":{  
        "result":"${..output}"
    },
    "type":"SIMPLE",
    "startDelay":0
  }
}

In the above example If I want to get decision task output, May I know how we can give json path expression in next task.

I tried below expression it is not working for me.

"inputParameters":{  
        "result":"${..output}"
 }

**Note**:  If I give ${decide1.output}, it is returning output as below.
    "result": {
        "caseOutput": [
            "Show"
        ]
    }
}"

**Comment by kishorebanala** [comment] 2019-02-12 00:21
This is a duplicate of #953 , for which there is a PR in review: #979. Please follow the progress there.

**Closed by kishorebanala** 2019-02-12 00:21 UTC
