### ISSUE TITLE
TERMINATE task with "FAILED" terminationStatus doesn't trigger failureWorkflow

### ISSUE THREAD

**Issue by krishnaputhran** [Netflix/conductor#1750] opened 2020-06-25 04:10 UTC
Hi I have a workflow for which failureWorkflow is configured. During my workflow, at some places i have TERMINATE task to fail the workflow based on some conditions. But as of now I observe that TERMINATE task doesn't trigger the failureWorkflow, even if the terminationStatus is set to FAILED. Since its a failure of the workflow, and as per the explanation of failureWorkflow attribute, I expected it would trigger failureWorkflow.

**Comment by apanicker-nflx** [comment] 2020-06-29 23:36
Duplicate of #1328

**Closed by apanicker-nflx** 2020-06-29 23:36 UTC
