### ISSUE TITLE
Subworkflow doesn't return output

### ISSUE THREAD

**Issue by btafarelo** [Netflix/conductor#1849] opened 2020-08-28 19:40 UTC
Hi!

I made a subworkflow to organize some variables and there isn't an output but the workflow show the output correctly.

On my second screenshoot there is my last attempt in make it works, where I have set a hardcode variable.

Other subflows work fine but this one doesn't. This sub/workflow only has lambda tasks.

`{
      "name": "FORK_VARIABLES",
      "taskReferenceName": "FORK_VARIABLES",
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
           "name": "sumSF",
           "taskReferenceName": "sumSF",
           "type": "LAMBDA",
           "inputParameters": {
               "sf": "${workflow.input.sf}",
               "scriptExpression": "var r=0; for(var i=0; i<$.sf.length; i++) r += $.sf[i].amount; return r;"
           }
          }
        ],
        [
          {
           "name": "sumIO",
           "taskReferenceName": "sumIO",
           "type": "LAMBDA",
           "inputParameters": {
               "io": "${workflow.input.io}",
               "scriptExpression": "var r=0; for(var i=0; i<$.io.length; i++) r += $.io[i].amount; return r;"
           }
          }
        ],
        [
          {
           "name": "sumTX",
           "taskReferenceName": "sumTX",
           "type": "LAMBDA",
           "inputParameters": {
               "tx": "${workflow.input.tx}",
               "rfe": "${workflow.input.rfe}",
               "scriptExpression": "var r=0; for(var i=0; i<$.tx.length; i++) if ($.rfe == true && $.tx[i].taxType == 'TC') continue; else if ($.tx[i].status == 'On') r += $.tx[i].amount; return r;"
           }
          }
        ],
        [
          {
            "name": "digitDocument",
            "taskReferenceName": "digitDocument",
            "type": "LAMBDA",
            "inputParameters": {
                "cpf": "${workflow.input.cpf}",
                "scriptExpression": "return $.cpf.charAt(5) + '' + $.cpf.charAt(6);"
            }
          }
        ],
        [
          {
            "name": "financingProdutoApplied",
            "taskReferenceName": "financingProdutoApplied",
            "type": "LAMBDA",
            "inputParameters": {
                "input": "${workflow.input.financingProductId}",
                "dp": "${workflow.input.dp}",
                "scriptExpression": "var i = new String($.input); var v; for(var x=0;x<$.dp.length;x++) if ($.dp[x].name == 'Financing Product') v = $.dp[x].value; return (i != null && i.trim() != '' ? $.input : v)"
            }
          }
        ],
        [
          {
            "name": "remuneracaoApplied",
            "taskReferenceName": "remuneracaoApplied",
            "type": "LAMBDA",
            "inputParameters": {
                "input": "${workflow.input.remuneration}",
                "dp": "${workflow.input.dp}",
                "scriptExpression": "var i = new String($.input); var v; for(var x=0;x<$.dp.length;x++) if ($.dp[x].name == 'Remuneration') v = $.dp[x].value; return (i != null && i.trim() != '' ? $.input : v)"
            }
          }
        ],
        [
          {
           "name": "term",
           "taskReferenceName": "term",
           "type": "LAMBDA",
           "inputParameters": {
               "input": "${workflow.input.term}",
               "dp": "${workflow.input.dp}",
               "scriptExpression": "var i = new String($.input); var v; for(var x=0;x<$.dp.length;x++) if ($.dp[x].name == 'Term') v = $.dp[x].value; return (i != null && i.trim() != '' ? $.input : v)"
           }
          }
        ],
        [
          {
           "name": "inputPercentApplied",
           "taskReferenceName": "inputPercentApplied",
           "type": "LAMBDA",
           "inputParameters": {
               "ia": "${workflow.input.ia}",
               "vv": "${workflow.input.vv}",
               "sumSF": "${sumSF.output.result}",
               "sumIO": "${sumIO.output.result}",
               "scriptExpression": "return $.ia / ($.vv + $.sumSF + $.sumIO);"
           }
          },
          {
           "name": "inputAmountApplied",
           "taskReferenceName": "inputAmountApplied",
           "type": "LAMBDA",
           "inputParameters": {
               "ia": "${workflow.input.ia}",
               "ip": "${inputPercentApplied.output.result}",
               "vv": "${workflow.input.vv}",
               "sumSF": "${sumSF.output.result}",
               "sumIO": "${sumIO.output.result}",
               "scriptExpression": "return $.ip * ($.vv + $.sumSF + $.sumIO);"
           }
          },
          {
           "name": "financedValueApplied",
           "taskReferenceName": "financedValueApplied",
           "type": "LAMBDA",
           "inputParameters": {
               "vv": "${workflow.input.vv}",
               "iap": "${inputAmountApplied.output.result}",
               "sumSF": "${sumSF.output.result}",
               "sumIO": "${sumIO.output.result}",
               "sumTX": "${sumTX.output.result}",
               "scriptExpression": "return ($.vv + $.sumSF + $.sumIO + $.sumTX) - $.iap;"
           }
          }
        ]
      ]
    },
    {
      "name": "JOIN_VARIABLES",
      "taskReferenceName": "JOIN_VARIABLES",
      "type": "JOIN",
      "joinOn": [
        "digitDocument",
        "financingProdutoApplied",
        "remuneracaoApplied",
        "term",
        "financedValueApplied",
        "sumSF",
        "sumIO",
        "sumTX"
      ]
    }`

Subworkflow without output
![image](https://user-images.githubusercontent.com/3848106/91608981-d3613f80-e976-11ea-8cce-9c45390c08f5.png)

Workflow with output
![image](https://user-images.githubusercontent.com/3848106/91609051-f855b280-e976-11ea-9781-dd93e00b2d3d.png)

**Comment by kishorebanala** [comment] 2020-09-01 00:07
Hey @btafarelo , Can you let us know what your `JOIN_VARIABLES` task output looks like?

Join task should contain all the output data from tasks it is joining on, as key value pairs, where key being the task reference name from joinOn array.

And if `JOIN_VARIABLES` is the last task in workflow, the workflow output should be copied over from this task, *unless* the workflow output is parameterized to selectively pick output values from last task's output.

**Comment by btafarelo** [comment] 2020-09-17 08:07
Hi @kishorebanala sorry my late notice!!!

Here is the join variables, now it would be slight different as to make the things work I made many refactorings, but this fork still doing the same things, split some tasks just to set "variables". It isn't a sub workflow anymore but should be.

`{
            "name": "JOIN_VARIABLES",
            "taskReferenceName": "JOIN_VARIABLES",
            "type": "JOIN",
            "joinOn": [
              "digitDocument",
              "financingProdutoApplied",
              "remuneracaoApplied",
              "term",
              "financedValueApplied"
            ]
          },`

What I have noticed is when my sub workflow doesn't have any http task it doesn't return any output.

At that time, I had not outputParameters sat but I also did many tests and one of them was set a hardcode outputParameter

**Comment by btafarelo** [comment] 2020-10-10 17:19
After a long time implementing other stuffs on the project I finally returned to conductor development in my project. This first subworkflow that I have commented doesn't exist anymore just because I gave up to use this feature when I don't have any HTTP taks inside it as this is the only way that makes the subworkflow return the ouput. Now I'm facing the same issue again. I made a subworkflow with JSON_JQ_TRANSFORM tasks only, and the last task is returning the output correctly, I settled the outputParameters on the workflow to force the ouput but there's no way to get the result on the parent flow.

Conductor version: 2.31.0-SNAPSHOT

here is the subworkflow on the parent flow
![image](https://user-images.githubusercontent.com/3848106/95661131-1fce9c00-0b2d-11eb-9a64-3451cf421292.png)

here is the subworkflow on itself
![image](https://user-images.githubusercontent.com/3848106/95661150-4f7da400-0b2d-11eb-8290-682bca1d3ddc.png)

Here is subworkflow code:
`{
  "createTime": 1598614840535,
  "name": "simulation_execution_response",
  "description": "response",
  "version": 1,
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "btafarelo@gmail.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "outputParameters": {
    "vsfd": "${RootJson.output.result}"
  },
  "tasks": [
    {
      "name": "LinksJson",
      "taskReferenceName": "LinksJson",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "so": "${workflow.input.serviceOffer}",
        "io": "${workflow.input.insuranceOffer}",
        "links": {
          "serviceOffers": {"href": []},
          "insuranceOffers": {"href": []},
          "offerPackages": {"href": []}
        },
        "queryExpression": ".links.serviceOffers.href += (.so | map(.links.self.href)) | .links"
      }
    },
    {
      "name": "FinancingOfferJson",
      "taskReferenceName": "FinancingOfferJson",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "fo": "${workflow.input.financingOffer}",
        "queryExpression": ".fo | map({\"offerId\": .offerId,\"description\": .description,\"repackageId\": null,\"product\": {\"productId\": null, \"description\": null},\"coefficient\": null,\"couponCodeApplied\": null,\"inputAmountApplied\": null,\"inputPercentApplied\": null,\"maxInputPercent\": null,\"minInputPercent\": null,\"financedAmountApplied\": null,\"maxFinancedAmountPercent\": null,\"minFinancedAmountPercent\": null,\"delays\": null,\"delayApplied\": null,\"terms\": null,\"termApplied\": null,\"commissions\": null,\"commissionApplied\": null,\"remunerations\": null,\"remunerationApplied\": null,\"taxesApplied\": null,\"paymentPlan\": {  \"customerFee\": null,  \"monthlyInterestRate\": null,  \"annualInterestRate\": null,  \"installments\": null},\"serviceOffers\": null,\"insuranceOffers\": null,\"offerPackages\": null,\"links\": null})"
      }
    },
    {
      "name": "FinancingOfferLinksJson",
      "taskReferenceName": "FinancingOfferLinksJson",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "fo": "${FinancingOfferJson.output.result}",
        "links": "${LinksJson.output.result}",
        "queryExpression": ".fo[].links = .links | .fo"
      }
    },
    {
      "name": "RootJson",
      "taskReferenceName": "RootJson",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "fo": "${FinancingOfferLinksJson.output.result}",
        "p": {
          "simulationId": null,
          "simulationType": "${workflow.input.simulationType}",
          "exibitionOrder": null,
          "initialPeriod": null,
          "finalPeriod": null,
          "financingBrand": "${workflow.input.req.financingBrand}",
          "saleType": "${workflow.input.req.saleType}",
          "customer": {
            "personType": "${workflow.input.req.personType}",
            "cpfCnpj": "${workflow.input.req.customerCpfCnpj}",
            "name": null,
            "guarantor": {"cpf": null, "name": null}
          },
          "registrationFeeExemption": "${workflow.input.req.registrationFeeExemption}",
          "vehicleVersionId": "${workflow.input.req.vehicleVersionId}",
          "vehicleValue": "${workflow.input.req.vehicleValue}",
          "specialVehicleType": "${workflow.input.req.specialVehicleType}",
          "vehicleQuantity": "${workflow.input.req.vehicleQuantity}",
          "dealershipId": "${workflow.input.req.dealershipId}",
          "financingOffers": null
        },
        "queryExpression": ".p.financingOffers = .fo | .p"
      }
    }
  ]
}
`

**Comment by btafarelo** [comment] 2020-10-11 09:37
After to add this task bellow on my subworkflow, I'm able to get its output on the parent flow. As you can see this task doesn't make any thing, it is just necessary to make the subworkflow return the result.

{
      "name": "Mock",
      "taskReferenceName": "Mock",
      "optional": "true",
      "type": "HTTP",
      "inputParameters": {
        "http_request": {
          "uri": "${workflow.input.req.url}",
          "method": "GET"
        }
      }
    },

![image](https://user-images.githubusercontent.com/3848106/95675255-248b6280-0bb6-11eb-842c-352c5bb3f430.png)

**Comment by kishorebanala** [comment] 2020-10-13 23:40
@btafarelo Looking at `"outputParameters": { "vsfd": "${RootJson.output.result}" }` in Workflow definition, What is the result of Task `RootJson`? If this task's output has an object `result` in the json, it should be populated to the Subworkflow output.

**Comment by pweatherby-ccctc** [comment] 2020-11-11 01:28
I am using release v2.30.1 of conductor. I too am experiencing a similar issue in which the output of a subworkflow is not bubbling up to the parent workflow. My issue is also solved by adding a temp/mock/stupid http task as the first tasking within the subworkflow. This indicates to me that there is a race condition present; that the subworkflow is completing too quickly. by adding a http call, it slows the subworkflow down enough to avoid the race condition.

In looking at line 118 of the subworkflow file (https://github.com/Netflix/conductor/blob/d4c550f38020ba58b312cf2299361af294ebd3f0/core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java#L118). I see we are setting the parent workflow's task status based on subworkflow's current status noting that the status could've changed by the time we get to that line (since its creation a few lines above). If the subworkflow has completed at that point (still in the start function), the task is marked as complete, but the subworkflow's output is not copied to the tasks' output. Then when the executor engine fires the first execute function call, the task is already in the complete stage and the output is not copied over.

I would recommend that someone adjust line 118 to add copying over the output data if the subworkflow is already complete at that point.

**Comment by kishorebanala** [comment] 2020-11-17 00:36
@pweatherby-ccctc Thanks for helping trace the root cause. I'll reproduce and prioritize a bugfix asap.

**Comment by btafarelo** [comment] 2020-11-23 17:49
Hi guys, sorry but I don't get any alert from this thread or maybe from any thread in this repository. Can I provide something to help?

**Comment by sukruthiarjula** [comment] 2020-11-24 16:04
Hi ,

I have fixed the issue and raised the PR https://github.com/Netflix/conductor/pull/1984 .

@btafarelo @kishorebanala @pweatherby-ccctc

**Comment by apanicker-nflx** [comment] 2020-12-08 00:25
Closing since #1984 is merged

**Closed by apanicker-nflx** 2020-12-08 00:25 UTC
Labels: bug, help wanted
