### ISSUE TITLE
Unimplemented QueueDAO.containsMessage() for mysql & postgres

### ISSUE THREAD

**Issue by willqiao** [Netflix/conductor#1892] opened 2020-09-30 03:56 UTC
Hi Conductor Team,

We are using conductor with postgres database(previously, we were using mysql). After switching to both of the DBs, we found there is a WorkflowRepairService trying to call QueueDAO.containsMessage(). However, both Mysql and Postgres impl doesnt have this containsMessage() implemented. Logs will constantly throws following exceptions. I tried to put a 
workflow.repairservice.enabled=false in config.properties, hoping it can disable this function, but couldnt. 

I'm asking 2 questions here:
1. This exception doesnt seems a blocker for using any workflow API. Do we know what this WorkflowRepairService does?
2. Is it on purpose to not implement this containsMessage() for Mysql/postgres implementation? Any reason behind it? If not, do we have an estimation when we can address this un-finished method?

Thanks.
Will

`421529 [pool-16-thread-2] ERROR com.netflix.conductor.core.execution.WorkflowSweeper  - Error running sweep for 87614879-4935-4a55-9a05-b287f532288f
java.lang.UnsupportedOperationException: Please ensure your provided Queue implementation overrides and implements this method.
	at com.netflix.conductor.dao.QueueDAO.containsMessage(QueueDAO.java:199)
	at com.netflix.conductor.core.execution.WorkflowRepairService.verifyAndRepairTask(WorkflowRepairService.java:118)
	at com.netflix.conductor.core.execution.WorkflowRepairService.lambda$verifyAndRepairWorkflowTasks$2(WorkflowRepairService.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.netflix.conductor.core.execution.WorkflowRepairService.verifyAndRepairWorkflowTasks(WorkflowRepairService.java:84)
	at com.netflix.conductor.core.execution.WorkflowSweeper.lambda$sweep$1(WorkflowSweeper.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by kishorebanala** [comment] 2020-10-01 01:39
Hey @willqiao , The `WorkflowRepairService` should be disabled by default for MySQL and Postgres QueueDAO implementation with this configuration parameter: https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/config/Configuration.java#L389

Can you verified if this is overwritten by any chance? This is only enabled for `redis-persistence` module at the moment.

> 1. This exception doesnt seems a blocker for using any workflow API. Do we know what this WorkflowRepairService does?

The `WorkflowRepairService` help ensure the relevant message exists in Queue for a given task, and repushes the message is a message is lost in the queue for any reason.  Please see https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowRepairService.java and relevant test(s) for more details.

> 2. Is it on purpose to not implement this containsMessage() for Mysql/postgres implementation? Any reason behind it? If not, do we have an estimation when we can address this un-finished method?

I see you've created a PR for this implementation in MySQL and Postgres, thank you! There's no reason and we wanted to add this incrementally.

**Comment by demichej** [comment] 2020-10-01 01:42
@kishorebanala there's a bug in general with how the Configuration is being bound. I've got a PR up to fix it. (But thank you too for fixing Mysql and Postgres @Yingsheng-eroad !!)

https://github.com/Netflix/conductor/pull/1895

The issue is that the core System properties configuration was always being bound to the Dynomite one.....so everything always get true. My PR changes it so that you have to explicitly set the config property to true if you want to take advantage of it (I don't think there's a way around that).

**Comment by kishorebanala** [comment] 2020-10-08 21:47
Fixed in https://github.com/Netflix/conductor/pull/1895,  https://github.com/Netflix/conductor/pull/1899,

**Closed by kishorebanala** 2020-10-08 21:47 UTC
