### ISSUE TITLE
HttpTask  - Unexpected character ('<' (code 60)): expected a valid value

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#98] opened 2017-02-23 09:46 UTC
Hi , 

I am getting below exception while executing the workflow.

586262 [qtp1860118977-42] ERROR com.netflix.conductor.contribs.http.HttpTask  - Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@3f2353ae; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@3f2353ae; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2332)
	at com.netflix.conductor.contribs.http.HttpTask.extractBody(HttpTask.java:192)
	at com.netflix.conductor.contribs.http.HttpTask.httpCall(HttpTask.java:158)
	at com.netflix.conductor.contribs.http.HttpTask.start(HttpTask.java:119)
	at com.netflix.conductor.core.execution.WorkflowExecutor.lambda$scheduleTask$6(WorkflowExecutor.java:394)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.netflix.conductor.core.execution.WorkflowExecutor.scheduleTask(WorkflowExecutor.java:386)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:244)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:260)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:260)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:260)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:260)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:260)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:157)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:121)
	at com.netflix.conductor.core.execution.WorkflowExecutor.startWorkflow(WorkflowExecutor.java:88)
	at com.netflix.conductor.server.resources.WorkflowResource.startWorkflow(WorkflowResource.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

Regards
ajay

**Comment by v1r3n** [comment] 2017-02-23 16:44
@ajayaks does the endpoint return an xml? Conductor will only parse JSON and if it cannot parse, will print the error and store the response as a string.  Your workflow should continue to run with XML being stored as string.  Let me know if that is not the case.

**Comment by ajayaks** [comment] 2017-02-23 19:43
no xml , but i am passing sql query in json.  Its having condition "age <=99". While creating or updating the workflow no problem but when i execute the flow its breaking and getting above issue.

**Comment by v1r3n** [comment] 2017-02-23 19:50
The exception is when reading the response.  Does the repose contain SQL query?  Can you wrap the query in double quotes - that will make it a valid JSON.

**Comment by v1r3n** [comment] 2017-03-04 16:10
@ajayaks let me know if the problem is still there - or if we can close the issue.

**Closed** 2017-04-16 05:21 UTC

**Comment by ciastirfry** [comment] 2018-07-25 04:13
We have the same issue. May I what has been done to fix it? 

2018-07-25 04:12:16,671 [http-nio-8080-exec-17] [ERROR] (o.a.a.n.r.NpmRemoteRepoHandler:457) - Error while parsing the response of a remote npm JSON query on 'https://github.com/font-awesome': Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.jfrog.storage.binstore.common.ReaderTrackingInputStream@11f4c528; line: 3, column: 2]
2018-07-25 04:12:17,630 [http-nio-8080-exec-23] [ERROR] (o.a.a.n.r.NpmRemoteRepoHandler:457) - Error while parsing the response of a remote npm JSON query on 'https://github.com/numeral': Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.jfrog.storage.binstore.common.ReaderTrackingInputStream@19ed9a90; line: 3, column: 2]
2018-07-25 04:12:19,574 [http-nio-8080-exec-23] [INFO ] (o.j.r.d.v.r.h.DockerV2LocalRepoHandler:529) - Fetching docker manifest for repo 'tgds/fincalc-api-sample' and tag 'latest' in repo 'docker-sc-release_local'
2018-07-25 04:12:19,743 [http-nio-8080-exec-26] [ERROR] (o.a.a.n.r.NpmRemoteRepoHandler:457) - Error while parsing the response of a remote npm JSON query on 'https://github.com/jquery': Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
