### ISSUE TITLE
Long gaps between HTTP tasks lead to long overall execution time

### ISSUE THREAD

**Issue by xerxeArt** [Netflix/conductor#1183] opened 2019-06-07 13:17 UTC
Hello,
I have a workflow that looks like this: HTTP task -> DECISION task -> another HTTP task.

The 2 HTTP tasks take around 300ms each and the DECISION one takes 150ms. So together they would be under a second.
However, the time between one task finishes and the next one is starting is too long, sometimes >500ms, leading to more than doubling the execution time.

I have not implemented my own workers, so I am using what I think are the default ones.
I am running Conductor via docker-compose on my local machine.

I saw this was discussed already [here](https://github.com/Netflix/conductor/issues/952) , and here is what I have tried:

- in config.properties I added:
workflow.system.task.worker.poll.interval=10
workflow.system.task.worker.poll.count=1000
workflow.system.task.worker.thread.count=1000

- and in SystemTaskWorkerCoordinator.java, I changed
List<String> polledTaskIds = queueDAO.pop(taskName, realPollCount, 0); //the timeout was 200

But these changes did not improve the times.
Am I not getting this right?

Thanks,
Cristian

**Comment by naveenchlsn** [comment] 2019-06-07 15:53
Hi, @xerxeArt  Consider using async methods of index Dao. An api call to elastic search is made here. If this is made async, we have noticed that run times improve.

**Comment by xerxeArt** [comment] 2019-06-10 16:15
Hello @naveenchlsn Could you explain how I can do that?
In the meantime I changed the delay of scheduleWithFixedDelay from 1000 to 100 ms. No improvements. I'm just about ready to consider Netflix Conductor not fit for many small microservices.

**Comment by kishorebanala** [comment] 2019-06-11 23:12
@xerxeArt This is because Http task is async, which means the task is added to system task queue first, and then executed by a separate thread pool of system task workers later. This helps gaurd against the huge volume of long running http tasks eating up available thread pools and resources. You can disable this by flipping the async flag on Http task.

**Comment by xerxeArt** [comment] 2019-06-13 09:35
@kishorebanala thank you so much!!!
I had read somewhere that HTTP tasks were asynchronous in Conductor and not possible make synchronous.

Now I only need to find the sweet spot settings for best performance. By the way, can I update the configurations without needing to rebuild the docker image for Conductor Server?

**Comment by xerxeArt** [comment] 2019-06-14 06:36
After restarting the container, I'm back to the original 5 seconds per workflow run

I attached my task and workflow definitions and the config.properties file.

[taskdefs.txt](https://github.com/Netflix/conductor/files/3289272/taskdefs.txt)
[workflow.txt](https://github.com/Netflix/conductor/files/3289273/workflow.txt)

[config.properties.txt](https://github.com/Netflix/conductor/files/3289318/config.properties.txt)

And the execution times:
![ExecutionTimes](https://user-images.githubusercontent.com/30107426/59488180-81beb900-8e87-11e9-817a-e52da9fe9557.PNG)

Please, any

**Comment by kishorebanala** [comment] 2019-06-18 18:02
@xerxeArt The gap between Http tasks is because Conductor adds Http task to a queue instead of directly executing it (Http task is async:true). Whereas decision tasks are executed immediately.

If this is not your expected behavior, You can clone Conductor, change HttpTask's async to false and rebuild to generate your own jars.

**Comment by 0532** [comment] 2019-10-23 12:49
@xerxeArt  Hi , Do you solve the problem of processing performance of worker?

**Comment by 0532** [comment] 2019-10-23 13:15
@kishorebanala  sorry to interrupt，

I encountered the problem of worker pull performance, 
processing 445 per second, 
how to improve the processing capacity per second

* in config.properties I added:
 
   conductor.worker.longPollTimeout=0

   conductor.thread.pool.size=35
   
   conductor.queue.size=500
  
   conductor.worker.pollInterval=500

* and in SystemTaskWorkerCoordinator.java, I changed
 
   List polledTaskIds = queueDAO.pop(taskName, realPollCount, 0); //the timeout was 200

* clinet :
  
   mechines: 4servers  4c&8g
   
* server:
  
  mechines: 8servers  4c8g
   
  db is redis_cluster

**Comment by xerxeArt** [comment] 2019-10-27 14:17
@0532 nope, I ended up writing my own implementation of an orchestrator/integrator :)
I still have my docker-compose project with conductor somewhere, so if you find a solution, let me know so I can give it a shot also.

**Comment by 0532** [comment] 2019-10-28 01:10
> @0532 nope, I ended up writing my own implementation of an orchestrator/integrator :)
> I still have my docker-compose project with conductor somewhere, so if you find a solution, let me know so I can give it a shot also.
> 
> L.e.: 445 per second sounds like a dream! Are you sure that's not a typo?

No, this is exactly the number，But I want to know the best speed in the cluster deployment.

**Comment by kishorebanala** [comment] 2019-10-29 01:11
Given that Conductor schedules most of the tasks asynchronously through task queues, the latencies from polling the queues and processing messages through pools adds up to the lower bounds on task processing latency.

Conductor is designed to be an asynchronous system. In the next major release, We plan on using gRPC channels to avoid polling, and other configurable parameters for uses cases expecting high task throughput.

I'm closing this issue for now. Please feel free to reopen if you still have questions.

**Closed by kishorebanala** 2019-10-29 01:11 UTC

**Comment by coderrr22** [comment] 2022-08-23 19:53
> @xerxeArt The gap between Http tasks is because Conductor adds Http task to a queue instead of directly executing it (Http task is async:true). Whereas decision tasks are executed immediately.
> 
> If this is not your expected behavior, You can clone Conductor, change HttpTask's async to false and rebuild to generate your own jars.

Hi, You mean to simply change the isAsync() function on the HttpTask class to return a false value ? and that should change http tasks behavior to work synchronously ? Or should I change another part of the code ? Thanks !
