### ISSUE TITLE
Edit: Task timeoutSeconds not taking effect

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#362] opened 2017-11-10 20:57 UTC
Hi,

Is there a brief rundown on how the task "timeoutSeconds" and "responseTimeoutSeconds" works?  We have read all documentation but behavior does not seem to be what we expect.

From documentation for timeoutSeconds:
"Time in milliseconds, after which the task is marked as TIMED_OUT if not completed after transiting to IN_PROGRESS status"

Steps taken:
1. Start workflow with task_1 with timeoutSeconds as 120 seconds.
2. Poll for task_1 (this puts it IN_PROGRESS and updates the startTime)
3.  Wait for 5 minutes (300 seconds)  <==== After doing this, the task is still IN_PROGRESS and not TIMED_OUT.
4.  If then putting the same task IN_PROGRESS then it goes into "TIMED_OUT".

Questions:
1. Is there a specific trigger that needs to be invoked for a task to go into TIMED_OUT?  (aka there is no internal timer that will mark the task as TIMED_OUT and reschedule it)?  We thought setting the timeoutSeconds would be sufficient.

2. After the task does get into "TIMED_OUT" state, a new task instance of the same task (task_1) is created and "SCHEDULED", but then when a task is polled again, it is getting the original task that was "TIMED_OUT" and putting it back "IN_PROGRESS" why is this?  My understanding is once it is TIMED_OUT it should not be somehow not timed out anymore.

This last part is a side note of our use case and wondering if it can be added:
We have a use case where we are not using the "poll" to query the tasks, but rather doing an "search" API for "SCHEDULED" tasks.  Then we are setting them "IN_PROGRESS" using the POST /tasks API to update the task IN_PROGRESS to denote that we are starting a specific task.  However in this case, the startTime of the Task is not being set as it is only set during the "poll".  Can we do a similar check in the task update that if the startTime is 0, and we are setting it IN_PROGRESS, then to update the "startTime"?  This is affecting us because if the startTime is not set, the timeoutSeconds is not taking effect and is immediately timing out once it is set IN_PROGRESS.

**Comment by saidatta** [comment] 2018-01-04 20:21
I am experiencing the same behavior? Were you able to figure out the issue?

**Comment by cquon** [comment] 2018-01-04 21:52
@saidatta In the code tasks are set/checked for timeout in "checkForTimeout" in "core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java".

The call trace for this is:
...

WorkflowExecutor.java: boolean decide(String workflowId)

DeciderService.java:  DeciderOutcome decide(Workflow workflow, WorkflowDef def)

DeciderService.java:  DeciderOutcome decide(final WorkflowDef def, final Workflow workflow, List<Task> preScheduledTasks)

DeciderService.java:  void checkForTimeout(TaskDef taskType, Task task)


This flow generally is hit in a couple cases:
1. An explicit API to start decision task for workflow. (/workflow/decide/{workflowId} PUT API)
2. Resuming a paused workflow
3. Updating a task (ie: if you marked a task FAILED/SUCCESS it goes through the decide to determine what task to schedule next).
4. By a Workflow Sweeper (WorkflowSweeper.java) which pops from the queues and calls the decision, but this is disabled by default.

I have enabled the Workflow Sweeper and have been able to see tasks timed out.  Hopefully this helps.

This can be enabled in ServerModule.java

Add import:
import com.netflix.conductor.core.execution.WorkflowSweeper;

Add line:
bind(WorkflowSweeper.class).asEagerSingleton(); in the configure() method.
```
	@Override
	protected void configure() {
		
		configureExecutorService();
		
		bind(Configuration.class).toInstance(config);

		if (db == ConductorServer.DB.mysql) {
			install(new MySQLWorkflowModule());
		} else {
			String localDC = localRack;
			localDC = localDC.replaceAll(region, "");
			DynoShardSupplier ss = new DynoShardSupplier(hs, region, localDC);
			DynoQueueDAO queueDao = new DynoQueueDAO(dynoConn, dynoConn, ss, config);

			bind(MetadataDAO.class).to(RedisMetadataDAO.class);
			bind(ExecutionDAO.class).to(RedisExecutionDAO.class);
			bind(DynoQueueDAO.class).toInstance(queueDao);
			bind(QueueDAO.class).to(DynoQueueDAO.class);

			DynoProxy proxy = new DynoProxy(dynoConn);
			bind(DynoProxy.class).toInstance(proxy);
			bind(WorkflowSweeper.class).asEagerSingleton();  // ADD THIS LINE
		}
...
```

**Comment by saidatta** [comment] 2018-01-04 22:30
I would like to thank you for posting this. Do you happen to know why it is disabled by default? 
For performance issues?

**Comment by cquon** [comment] 2018-01-04 22:54
Possibly.  Query was here:
https://github.com/Netflix/conductor/issues/333

**Comment by akashbhunchal** [comment] 2018-01-20 14:35
Sorry for opening this up again, but I have been going through the code and trying my luck for a whole day now :(

My understanding of these two parameters goes like this : 

responseTimeoutSeconds : Suppose its 60 secs. If one worker picks up a task, it goes into IN_PROGRESS . Now if this task is not updated with a SUCCESS/FAILURE in the next 60 secs , if not then this task should go back to queue and if another worker is polling, it should be picked up by that worker.

timeoutSeconds: Suppose this is 300 secs. Irrespective of the Poll Count, if a task is not SUCCESS?FAILED in this time duration, it would be TIMED_OUT.

I have added the line to the code as suggested, but for me both of them are not working. Is my understanding correct ?

One thing I have noticed is that I have set these value (responseTimeoutSeconds/timeoutSeconds) in the taskDef, but when I get the task object both of them are 0. I even tried setting them in the workFlowDef (in the takss list), still the same. I believe this is the issue for me , but am not sure what to do

**Comment by akashbhunchal** [comment] 2018-01-21 09:20
I see that the in Task.java
```
@Deprecated
	public int getResponseTimeoutSeconds() {
		return 0;
	}
```
This has been deprecated and a 0 is being returned. I belive this is by design. I even changed this to return the actual value. I now get the correct value in the workflow task object (not 0 always), but the responseTimeout happens in an erratic manner. If I set it to 150 secs, it somethimes timesout in 90 secs and sometimes in 119 secs.

I guess we are supposed to use version 2 everywhere . Even that didnt help. Here are my objects that I use to create task, workflow and start workflow

```
[
  {
    "ownerApp": "AWS CG",
    "createdBy": "Akash",
    "name": "Billing File Ingestion",
    "description": "Task to Ingest AWS billing file",
    "retryCount": 0,
    "timeoutSeconds": 300,
    "inputKeys": [
      "inputKey1",
      "inputKey2"
    ],
    "outputKeys": [
      "outputKey1",
      "outputKey2"
    ],
    "timeoutPolicy": "RETRY",
    "retryLogic": "FIXED",
    "retryDelaySeconds": 0,
    "responseTimeoutSeconds": 150,
    "concurrentExecLimit": 100,
    "inputTemplate": {}
  }
]
```

This is for create a Workflow:
```
{
  "ownerApp": "AWS CG",
  "createdBy": "Akash",
  "name": "AWS CG Workflow",
  "description": "AWS Billing File Ingestion Workflow",
  "version": 2,
  "tasks": [
    {
      "name": "Billing File Ingestion",
      "taskReferenceName": "Billing File Ingestion",
      "description": "Billing File Ingestion",
      "inputParameters": {},
      "type": "SIMPLE",
      "startDelay": 0,
      "sink": "conductor",
      "optional": false
    }
  ],
  "inputParameters": [
    "inputKey1",
    "inputKey2"
  ],
  "outputParameters": {},
  "schemaVersion": 0
}
```

This is for starting the workflow:

```
{
  "name": "AWS CG Workflow",
  "version": 2,
  "input": {
  	"inputKey1":"value1",
    "inputKey2":"value2"},
  "taskToDomain": {}
}
```

I am trying to get the responseTimeoutSeconds to work as designed (if my understanding is correct).

**Comment by LiranBri** [comment] 2019-01-06 15:41
@cquon what do by "putting task back in IN_PROGRESS" you mean you tried to poll the task again?

**Comment by cyzhao** [comment] 2019-01-13 21:39
we will look into enabling sweeper by default, see #333, closing this.

**Closed by cyzhao** 2019-01-13 21:39 UTC
