### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by arjunbiyani** [Netflix/conductor#2207] opened 2021-04-25 18:03 UTC
While running Docker compose up  ,  build is failing 

**To Reproduce**
1. cd docker 
2. docker-compose up

**Screenshots**
Docker Compose is now in the Docker CLI, try `docker compose up`

Building conductor-server
[+] Building 125.6s (12/16)
 => [internal] load build definition from Dockerfile                                                                                                          0.0s
 => => transferring dockerfile: 891B                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/openjdk:8-jre-alpine                                                                                       2.8s
 => [internal] load metadata for docker.io/library/openjdk:8-jdk                                                                                              2.8s
 => [auth] library/openjdk:pull token for registry-1.docker.io                                                                                                0.0s
 => [internal] load build context                                                                                                                             1.0s
 => => transferring context: 26.25MB                                                                                                                          0.9s
 => [stage-1 1/6] FROM docker.io/library/openjdk:8-jre-alpine@sha256:f362b165b870ef129cbe730f29065ff37399c0aa8bcab3e44b51c302938c9193                         0.0s
 => CACHED [builder 1/4] FROM docker.io/library/openjdk:8-jdk@sha256:9c973bec7c011abcd4c64c5d8601073d26c9d6dd17ca58ea0df5cda98f0e5b05                         0.0s
 => CACHED [stage-1 2/6] RUN mkdir -p /app/config /app/logs /app/libs                                                                                         0.0s
 => [builder 2/4] COPY . /conductor                                                                                                                           0.3s
 => [builder 3/4] WORKDIR /conductor                                                                                                                          0.0s
 => ERROR [builder 4/4] RUN ./gradlew build -x test                                                                                                         121.4s
------
 > [builder 4/4] RUN ./gradlew build -x test:
#12 0.671 Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
#12 1.623 ..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%
#12 9.553
#12 9.554 Welcome to Gradle 6.8.3!
#12 9.554
#12 9.555 Here are the highlights of this release:
#12 9.556  - Faster Kotlin DSL script compilation
#12 9.557  - Vendor selection for Java toolchains
#12 9.558  - Convenient execution of tasks in composite builds
#12 9.558  - Consistent dependency resolution
#12 9.560
#12 9.561 For more details see https://docs.gradle.org/6.8.3/release-notes.html
#12 9.562
#12 9.937 Starting a Gradle Daemon (subsequent builds will be faster)
#12 78.73
#12 78.74 > Configure project :conductor-azureblob-storage
#12 78.74 Inferred project: conductor, version: 3.1.0-SNAPSHOT
#12 105.6
#12 105.6 > Task :processResources NO-SOURCE
#12 105.7 > Task :compileJava NO-SOURCE
#12 105.7 > Task :classes UP-TO-DATE
#12 105.8 > Task :createPropertiesFileForJar
#12 105.9 > Task :writeManifestProperties
#12 106.0 > Task :jar
#12 107.1 > Task :startScripts
#12 107.2 > Task :distTar
#12 107.2 > Task :distZip
#12 107.2 > Task :assemble
#12 107.2 > Task :check
#12 107.2 > Task :conductor-azureblob-storage:processResources NO-SOURCE
#12 107.2 > Task :conductor-common:processResources NO-SOURCE
#12 119.5 > Task :conductor-common:compileJava FAILED
#12 119.5
#12 119.5 FAILURE: Build failed with an exception.
#12 119.5
#12 119.5 * What went wrong:
#12 119.5 Execution failed for task ':conductor-common:compileJava'.
#12 119.5 > invalid flag: --release
#12 119.5
#12 119.5 * Try:
#12 119.5 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 119.5
#12 119.5 * Get more help at https://help.gradle.org
#12 119.5
#12 119.5 BUILD FAILED in 1m 59s
#12 119.5 7 actionable tasks: 7 executed
#12 119.7
#12 119.7 Publishing build scan...
#12 120.6 https://gradle.com/s/qh4lamiaf4cgy
#12 120.6
------
executor failed running [/bin/sh -c ./gradlew build -x test]: exit code: 1
ERROR: Service 'conductor-server' failed to build

**Comment by komatiraju032** [comment] 2021-04-25 18:19
Duplicate of #2198

**Comment by maheshyaddanapudi** [comment] 2021-04-25 20:27
PR Raised https://github.com/Netflix/conductor/pull/2206

**Comment by aravindanr** [comment] 2021-05-10 23:12
This is addressed as part of [v3.0.3](https://github.com/Netflix/conductor/releases/tag/v3.0.3)

**Closed by aravindanr** 2021-05-10 23:12 UTC
Labels: type: bug
