### ISSUE TITLE
Search workflow API returns weird results

### ISSUE THREAD

**Issue by flavioschuindt** [Netflix/conductor#1666] opened 2020-05-01 02:20 UTC
Hi, guys.

While using the search API, I see some weird results:

* Query all workflows execution with query **status="FAILED" OR status="TERMINATED" or status="TIMED_OUT"** (```api/workflow/search?query=status="FAILED" OR status="TERMINATED" or status="TIMED_OUT"&start=0&size=100```) and I get this:

```
{
    "totalHits": 37,
    "results": [
        {
            37 entries here....
        }
}
```

* Query all workflows execution with query **status="TIMED_OUT"** (```api/workflow/search?query=or status="TIMED_OUT"&start=0&size=100```) and I get this:

```
{
    "totalHits": 61,
    "results": [
        { 
            61 entries here....
        }
}
```

How is that possible? I would expect the first result to be at least greater or equal to the second one. Second one is a subset of the first. And in the second one I see a lot of entries that are not presented in the first one.

Thank you!

**Comment by apanicker-nflx** [comment] 2020-05-11 23:44
@flavioschuindt Would it be possible to get the ES query that the client makes for each of these requests. You could set breakpoints in your local server to help debug this faster.

**Comment by flavioschuindt** [comment] 2020-06-09 01:15
Hey @apanicker-nflx, unfortunately this was in some of the test env that someone wiped out and I didn't have the opportunity to see the logs before they were wiped out.

**Comment by apanicker-nflx** [comment] 2020-06-15 23:44
I tried running this in our test environment and was not able to reproduce this. I will close this issue for now, please reopen if you run into this again.

**Closed by apanicker-nflx** 2020-06-15 23:44 UTC
